-- 全局计算机术语词典（ASR 热词纠错方案 3.2）
-- 拼音为无声调读音序列（空格分隔）；多音字可用 | 分隔候选读音（索引构建时展开）。
-- 不向量化、不进知识库：仅服务拼音检索纠错（语义向量对同音错字检索失效）。
CREATE TABLE term_dict (
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    term        VARCHAR(128) NOT NULL COMMENT '规范术语，如 Raft、零拷贝、MVCC',
    pinyin      VARCHAR(256) NOT NULL COMMENT '空格分隔读音序列，如 la fu te / ling kao bei（多音字用 | 分隔候选）',
    category    VARCHAR(32)  DEFAULT NULL,
    aliases     VARCHAR(512) DEFAULT NULL COMMENT 'JSON 数组：别名/常见错误写法，如 ["springboot","spring boot"]',
    enabled     TINYINT(1)   DEFAULT 1,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_term (term)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='全局计算机术语词典（拼音检索用，不向量化）';

-- 种子词表：八股高频术语首批播种（英文按中文使用者常见读音转写，缩写按字母名读音）。
-- 后续可由 LLM 从知识库文档批量抽取扩充至 1000~2000 条（人工抽查优先英文发音歧义词）。
INSERT INTO term_dict (term, pinyin, category, aliases) VALUES
-- 中间件 / 存储
('Redis', 'rui di si', 'middleware', '["redis"]'),
('Kafka', 'ka fu ka', 'middleware', '["kafka"]'),
('RocketMQ', 'lao ke te em kiu', 'middleware', '["rocketmq"]'),
('RabbitMQ', 'rui bi te em kiu', 'middleware', '["rabbitmq"]'),
('消息队列', 'xi xi dui lie', 'middleware', '["mq"]'),
('MySQL', 'em wai es kju el', 'database', '["mysql"]'),
('PostgreSQL', 'po si te ge lei si kju el', 'database', '["postgres","postgresql"]'),
('MongoDB', 'meng ge di bi', 'database', '["mongodb"]'),
('Elasticsearch', 'yi la si ti ke se qi', 'database', '["es","elastic"]'),
('MVCC', 'em vei xi xi', 'database', '["mvcc"]'),
('B+树', 'bi jia shu', 'database', '["b+tree","b树","btree"]'),
('索引', 'suo yin', 'database', NULL),
('事务', 'shi wu', 'database', NULL),
('主从复制', 'zhu cong fu zhi', 'database', NULL),
('分库分表', 'fen ku fen biao', 'database', NULL),
('乐观锁', 'le guan suo', 'database', NULL),
('悲观锁', 'bei guan suo', 'database', NULL),
('死锁', 'si suo', 'database', NULL),
-- 框架
('Spring Boot', 'si ping bu te', 'framework', '["springboot","spring boot"]'),
('Spring Cloud', 'si ping ke lao de', 'framework', '["springcloud","spring cloud"]'),
('MyBatis', 'mai bei ti si', 'framework', '["mybatis"]'),
('Netty', 'nei ti', 'framework', '["netty"]'),
('Dubbo', 'da bo', 'framework', '["dubbo"]'),
('Vue', 'wei you', 'framework', '["vue","vuejs"]'),
('React', 'rui ai ke te', 'framework', '["react"]'),
-- 算法
('Raft', 'la fu te', 'algorithm', '["raft"]'),
('Paxos', 'pa ke suo si', 'algorithm', '["paxos"]'),
('一致性哈希', 'yi zhi xing ha xi', 'algorithm', NULL),
('布隆过滤器', 'bu long guo lv qi', 'algorithm', '["bloomfilter"]'),
('跳表', 'tiao biao', 'algorithm', '["skiplist"]'),
('红黑树', 'hong hei shu', 'algorithm', '["redblacktree"]'),
('动态规划', 'dong tai gui hua', 'algorithm', NULL),
('贪心算法', 'tan xin suan fa', 'algorithm', NULL),
('双指针', 'shuang zhi zhen', 'algorithm', NULL),
('快速排序', 'kuai su pai xu', 'algorithm', NULL),
('归并排序', 'gui bing pai xu', 'algorithm', NULL),
('堆排序', 'dui pai xu', 'algorithm', NULL),
('二分查找', 'er fen cha zhao', 'algorithm', NULL),
('拓扑排序', 'tuo pu pai xu', 'algorithm', NULL),
('LRU', 'el ar you', 'algorithm', '["lru"]'),
('Dijkstra', 'dai ke si te la', 'algorithm', '["dijkstra"]'),
-- 协议 / 网络
('TCP', 'ti xi pi', 'protocol', '["tcp"]'),
('UDP', 'you di pi', 'protocol', '["udp"]'),
('HTTP', 'ei chi ti pi', 'protocol', '["http"]'),
('HTTPS', 'ei chi ti pi es', 'protocol', '["https"]'),
('三次握手', 'san ci wo shou', 'protocol', NULL),
('四次挥手', 'si ci hui shou', 'protocol', NULL),
('滑动窗口', 'hua dong chuang kou', 'protocol', NULL),
('DNS', 'di en es', 'protocol', '["dns"]'),
('CDN', 'xi di en', 'protocol', '["cdn"]'),
('负载均衡', 'fu zai jun heng', 'protocol', NULL),
('gRPC', 'ji a er pi xi', 'protocol', '["grpc"]'),
('WebSocket', 'wei sao ke te', 'protocol', '["websocket"]'),
-- 操作系统 / 云原生
('零拷贝', 'ling kao bei', 'system', NULL),
('epoll', 'yi po', 'system', '["epoll"]'),
('IO多路复用', 'ai ou duo lu fu yong', 'system', '["io多路复用","i/o多路复用","多路复用"]'),
('虚拟内存', 'xu ni nei cun', 'system', NULL),
('页缓存', 'ye huan cun', 'system', NULL),
('协程', 'xie cheng', 'system', NULL),
('Docker', 'dao ke', 'system', '["docker"]'),
('Kubernetes', 'ku bo nei ti si', 'system', '["k8s","kubernetes"]'),
('K8s', 'kei ba si', 'system', '["k8s","kubernetes"]'),
('微服务', 'wei fu wu', 'system', NULL),
('服务网格', 'fu wu wang ge', 'system', '["servicemesh"]'),
('etcd', 'yi ti xi di', 'system', '["etcd"]'),
-- 语言 / Java 并发
('Java', 'jia fa', 'language', '["java"]'),
('Golang', 'gou lang', 'language', '["golang","go语言"]'),
('Python', 'pai sen', 'language', '["python"]'),
('GIL', 'ji ai el', 'language', '["gil"]'),
('GC', 'ji xi', 'language', '["gc","垃圾回收"]'),
('JVM', 'jie vei em', 'language', '["jvm"]'),
('HashMap', 'ha xi ma pu', 'language', '["hashmap"]'),
('ConcurrentHashMap', 'kang ka lun te ha xi ma pu', 'language', '["concurrenthashmap"]'),
('volatile', 'wo la tai er', 'language', '["volatile","volatile关键字"]'),
('synchronized', 'xin ke rui nai zi de', 'language', '["synchronized","sync"]'),
('AQS', 'ei kiu es', 'language', '["aqs"]'),
('CAS', 'xi ei es', 'language', '["cas"]'),
('反射', 'fan she', 'language', NULL),
('泛型', 'fan xing', 'language', NULL),
-- 分布式
('CAP', 'kei ei pi', 'system', '["cap理论","cap"]'),
('BASE', 'bei si', 'system', '["base理论"]'),
('分布式锁', 'fen bu shi suo', 'system', NULL),
('分布式事务', 'fen bu shi shi wu', 'system', NULL),
('幂等', 'mi deng', 'system', NULL),
('限流', 'xian liu', 'system', NULL),
('熔断', 'rong duan', 'system', NULL),
('降级', 'jiang ji', 'system', NULL),
('缓存雪崩', 'huan cun xue beng', 'system', NULL),
('缓存穿透', 'huan cun chuan tou', 'system', NULL),
('缓存击穿', 'huan cun ji chuan', 'system', NULL);
