-- 全局计算机术语词典 二期扩充（ASR 热词纠错方案 3.2）
-- 拼音为无声调读音序列（空格分隔）；英文按中文使用者常见读音转写，缩写按字母名读音。
-- 一期(V12)已播种八股高频 90 条，本期按领域补充：AI / 计网 / 数据结构 / 操作系统 / Java / MySQL / Redis / MQ。
-- 不向量化、不进知识库：仅服务拼音检索纠错。
-- 注意：ReAct 用字母名读音 ru yi e xi ti，避免与前端 React(rui ai ke te) 拼音撞车。

-- 修正 V12 拼音笔误：消息队列应为 xiao xi dui lie（原 xi xi dui lie 会导致召回不到）
UPDATE term_dict SET pinyin = 'xiao xi dui lie', updated_at = NOW() WHERE term = '消息队列';

INSERT IGNORE INTO term_dict (term, pinyin, category, aliases) VALUES
-- ============ AI 方向 ============
('ReAct', 'ru yi e xi ti', 'ai', '["react","react推理"]'),
('Prompt', 'pu luo mu te', 'ai', '["prompt","提示词"]'),
('LLM', 'el el em', 'ai', '["llm","大语言模型"]'),
('Agent', 'ei jian te', 'ai', '["agent","智能体"]'),
('RAG', 'ar ei ji', 'ai', '["rag","检索增强生成"]'),
('Transformer', 'chuan si fuo ma', 'ai', '["transformer","transformer模型"]'),
('Embedding', 'en bei ding', 'ai', '["embedding","向量化"]'),
('微调', 'wei tiao', 'ai', '["finetune","fine-tune"]'),
('大模型', 'da mo xing', 'ai', '["llm","大语言模型"]'),
('向量数据库', 'xiang liang shu ju ku', 'ai', '["vector database","向量库"]'),
('Tokenizer', 'te ken nai za', 'ai', '["tokenizer","分词器"]'),
('注意力机制', 'zhu yi li ji zhi', 'ai', '["attention","注意力"]'),
('LoRA', 'el ou ar ei', 'ai', '["lora","低秩适配"]'),
('提示词工程', 'ti shi ci gong cheng', 'ai', '["prompt engineering","提示工程"]'),
('思维链', 'si wei lian', 'ai', '["chain of thought","cot"]'),
('多模态', 'duo mo tai', 'ai', '["multimodal"]'),
('幻觉', 'huan jue', 'ai', '["hallucination"]'),
('上下文窗口', 'shang xia wen chuang kou', 'ai', '["context window"]'),
('模型推理', 'mo xing tui li', 'ai', '["inference"]'),
('知识库', 'zhi shi ku', 'ai', '["knowledge base"]'),
('温度', 'wen du', 'ai', '["temperature"]'),
-- ============ 计算机网络 ============
('IP地址', 'ai pi di zhi', 'network', '["ip","ip地址"]'),
('TCP/IP', 'ti xi pi ai pi', 'network', '["tcpip","tcp/ip协议栈"]'),
('OSI', 'ou ei si ai', 'network', '["osi七层模型"]'),
('ARP', 'ei ar pi', 'network', '["arp"]'),
('ICMP', 'ai xi em pi', 'network', '["icmp"]'),
('NAT', 'en ei ti', 'network', '["nat","网络地址转换"]'),
('网关', 'wang guan', 'network', '["gateway"]'),
('子网掩码', 'zi wang yan ma', 'network', '["subnet mask"]'),
('端口', 'duan kou', 'network', '["port"]'),
('长连接', 'chang lian jie', 'network', NULL),
('短连接', 'duan lian jie', 'network', NULL),
('粘包', 'nian bao', 'network', NULL),
('拆包', 'chai bao', 'network', '["半包"]'),
('五元组', 'wu yuan zu', 'network', NULL),
('网卡', 'wang ka', 'network', '["nic"]'),
('交换机', 'jiao huan ji', 'network', '["switch"]'),
('路由器', 'lu you qi', 'network', '["router"]'),
('防火墙', 'fang huo qiang', 'network', '["firewall"]'),
('反向代理', 'fan xiang dai li', 'network', '["nginx"]'),
('正向代理', 'zheng xiang dai li', 'network', NULL),
('Nginx', 'en jin e ke si', 'network', '["nginx","反向代理"]'),
('SSL', 'es el el', 'network', '["ssl","tls"]'),
('证书', 'zheng shu', 'network', '["certificate"]'),
('对称加密', 'dui cheng jia mi', 'network', NULL),
('非对称加密', 'fei dui cheng jia mi', 'network', '["rsa"]'),
('数字签名', 'shu zi qian ming', 'network', '["signature"]'),
('拥塞控制', 'yong se kong zhi', 'network', NULL),
('流量控制', 'liu liang kong zhi', 'network', NULL),
('慢启动', 'man qi dong', 'network', NULL),
-- ============ 数据结构 ============
('数组', 'shu zu', 'datastructure', '["array"]'),
('链表', 'lian biao', 'datastructure', '["linked list"]'),
('栈', 'zhan', 'datastructure', '["stack"]'),
('队列', 'dui lie', 'datastructure', '["queue"]'),
('哈希表', 'ha xi biao', 'datastructure', '["hashtable","哈希"]'),
('哈希冲突', 'ha xi chong tu', 'datastructure', '["hash冲突","哈希碰撞"]'),
('二叉搜索树', 'er cha sou suo shu', 'datastructure', '["bst","二叉排序树"]'),
('AVL树', 'ei wei el shu', 'datastructure', '["avl","平衡二叉树"]'),
('Trie', 'te lai', 'datastructure', '["trie","字典树","前缀树"]'),
('堆', 'dui', 'datastructure', '["heap"]'),
('并查集', 'bing cha ji', 'datastructure', '["union find"]'),
('图', 'tu', 'datastructure', '["graph"]'),
('邻接表', 'lin jie biao', 'datastructure', NULL),
('邻接矩阵', 'lin jie ju zhen', 'datastructure', NULL),
('哈夫曼编码', 'ha fu man bian ma', 'datastructure', '["huffman"]'),
('字符串匹配', 'zi fu chuan pi pei', 'datastructure', '["kmp"]'),
('单调栈', 'dan diao zhan', 'datastructure', NULL),
('递归', 'di gui', 'datastructure', '["recursion"]'),
('分治', 'fen zhi', 'datastructure', '["divide and conquer"]'),
('回溯', 'hui su', 'datastructure', '["backtracking"]'),
('状态机', 'zhuang tai ji', 'datastructure', NULL),
('时间复杂度', 'shi jian fu za du', 'datastructure', '["复杂度"]'),
('空间复杂度', 'kong jian fu za du', 'datastructure', '["复杂度"]'),
-- ============ 操作系统 ============
('进程', 'jin cheng', 'system', '["process"]'),
('线程', 'xian cheng', 'system', '["thread"]'),
('线程池', 'xian cheng chi', 'system', '["thread pool"]'),
('用户态', 'yong hu tai', 'system', NULL),
('内核态', 'nei he tai', 'system', NULL),
('系统调用', 'xi tong tiao yong', 'system', '["syscall"]'),
('上下文切换', 'shang xia wen qie huan', 'system', '["context switch"]'),
('分页', 'fen ye', 'system', '["paging"]'),
('分段', 'fen duan', 'system', '["segmentation"]'),
('内存管理', 'nei cun guan li', 'system', '["mmu"]'),
('信号量', 'xin hao liang', 'system', '["semaphore"]'),
('互斥锁', 'hu chi suo', 'system', '["mutex"]'),
('条件变量', 'tiao jian bian liang', 'system', '["condition variable"]'),
('管道', 'guan dao', 'system', '["pipe"]'),
('共享内存', 'gong xiang nei cun', 'system', '["shared memory"]'),
('文件描述符', 'wen jian miao shu fu', 'system', '["fd","file descriptor"]'),
('阻塞IO', 'zu se ai ou', 'system', '["blocking io","阻塞io"]'),
('非阻塞IO', 'fei zu se ai ou', 'system', '["non-blocking io","非阻塞io"]'),
('进程调度', 'jin cheng tiao du', 'system', '["cpu调度"]'),
('时间片', 'shi jian pian', 'system', NULL),
('守护进程', 'shou hu jin cheng', 'system', '["daemon"]'),
('僵尸进程', 'jiang shi jin cheng', 'system', '["zombie"]'),
('孤儿进程', 'gu er jin cheng', 'system', NULL),
('内存泄漏', 'nei cun xie lou', 'system', '["memory leak"]'),
('栈溢出', 'zhan yi chu', 'system', '["stack overflow"]'),
-- ============ Java ============
('JDK', 'jie di kei', 'language', '["jdk"]'),
('JRE', 'jie ar yi', 'language', '["jre"]'),
('类加载', 'lei jia zai', 'language', '["classloader","类加载机制"]'),
('双亲委派', 'shuang qin wei pai', 'language', '["双亲委派模型"]'),
('垃圾回收', 'la ji hui shou', 'language', '["gc","垃圾回收器"]'),
('对象头', 'dui xiang tou', 'language', NULL),
('锁升级', 'suo sheng ji', 'language', NULL),
('偏向锁', 'pian xiang suo', 'language', NULL),
('轻量级锁', 'qing liang ji suo', 'language', NULL),
('重量级锁', 'zhong liang ji suo', 'language', NULL),
('自旋锁', 'zi xuan suo', 'language', '["spinlock"]'),
('读写锁', 'du xie suo', 'language', '["readwrite","reentrantreadwritelock"]'),
('可重入锁', 'ke chong ru suo', 'language', '["reentrantlock"]'),
('ThreadLocal', 'se de lao ke er', 'language', '["threadlocal","thread local"]'),
('内存屏障', 'nei cun ping zhang', 'language', '["memory barrier"]'),
('伪共享', 'wei gong xiang', 'language', '["false sharing"]'),
('强引用', 'qiang yin yong', 'language', '["strongreference"]'),
('弱引用', 'ruo yin yong', 'language', '["weakreference"]'),
('软引用', 'ruan yin yong', 'language', '["softreference"]'),
('虚引用', 'xu yin yong', 'language', '["phantomreference"]'),
('抽象类', 'chou xiang lei', 'language', '["abstract"]'),
('接口', 'jie kou', 'language', '["interface"]'),
('继承', 'ji cheng', 'language', '["inheritance"]'),
('多态', 'duo tai', 'language', '["polymorphism"]'),
('封装', 'feng zhuang', 'language', '["encapsulation"]'),
('Stream', 'si te rui mu', 'language', '["stream"]'),
('Lambda', 'lan mu da', 'language', '["lambda","lambda表达式"]'),
('序列化', 'xu lie hua', 'language', '["serializable"]'),
('注解', 'zhu jie', 'language', '["annotation"]'),
-- ============ MySQL ============
('InnoDB', 'yi nuo di bi', 'database', '["innodb"]'),
('MyISAM', 'mai ai sai mu', 'database', '["myisam"]'),
('隔离级别', 'ge li ji bie', 'database', '["isolation"]'),
('脏读', 'zang du', 'database', NULL),
('不可重复读', 'bu ke chong fu du', 'database', NULL),
('幻读', 'huan du', 'database', NULL),
('redo log', 're du lao ge', 'database', '["redo","重做日志"]'),
('undo log', 'an du lao ge', 'database', '["undo","回滚日志"]'),
('binlog', 'bin lao ge', 'database', '["binlog","二进制日志"]'),
('慢查询', 'man cha xun', 'database', '["慢sql"]'),
('覆盖索引', 'fu gai suo yin', 'database', NULL),
('最左前缀', 'zui zuo qian zhui', 'database', '["最左前缀原则"]'),
('回表', 'hui biao', 'database', NULL),
('索引下推', 'suo yin xia tui', 'database', '["icp","index condition pushdown"]'),
('间隙锁', 'jian xi suo', 'database', '["gap lock"]'),
('临键锁', 'lin jian suo', 'database', '["next-key lock"]'),
('读写分离', 'du xie fen li', 'database', NULL),
('连接池', 'lian jie chi', 'database', '["connection pool"]'),
('缓冲池', 'huan chong chi', 'database', '["buffer pool"]'),
('change buffer', 'chein ji ba fa', 'database', '["change buffer"]'),
('刷盘', 'shua pan', 'database', NULL),
('WAL', 'da bu liu ei el', 'database', '["wal","预写日志"]'),
('崩溃恢复', 'beng kui hui fu', 'database', '["crash recovery"]'),
('两阶段提交', 'liang jie duan ti jiao', 'database', '["2pc"]'),
('聚簇索引', 'ju cu suo yin', 'database', '["clustered index","聚集索引"]'),
('二级索引', 'er ji suo yin', 'database', '["非聚簇索引","secondary index"]'),
-- ============ Redis ============
('RDB', 'ar di bi', 'middleware', '["rdb"]'),
('AOF', 'ei ou ei fu', 'middleware', '["aof"]'),
('持久化', 'chi jiu hua', 'middleware', '["persistence"]'),
('哨兵', 'shao bing', 'middleware', '["sentinel"]'),
('集群', 'ji qun', 'middleware', '["cluster"]'),
('过期策略', 'guo qi ce lue', 'middleware', '["ttl"]'),
('淘汰策略', 'tao tai ce lue', 'middleware', '["eviction"]'),
('缓存一致性', 'huan cun yi zhi xing', 'middleware', NULL),
('双写', 'shuang xie', 'middleware', NULL),
('延迟双删', 'yan chi shuang shan', 'middleware', NULL),
('ZSet', 'zei set', 'middleware', '["zset","有序集合"]'),
('List', 'lie si te', 'middleware', '["list"]'),
('Hash', 'ha xi', 'middleware', '["hash"]'),
('String', 'si te rui ying', 'middleware', '["string"]'),
('Set', 'se te', 'middleware', '["set"]'),
('Bitmap', 'bi te ma pu', 'middleware', '["bitmap","位图"]'),
('HyperLogLog', 'hai pu er lao ge lao ge', 'middleware', '["hyperloglog","hll"]'),
('压缩列表', 'ya suo lie biao', 'middleware', '["ziplist"]'),
('快速列表', 'kuai su lie biao', 'middleware', '["quicklist"]'),
('大Key', 'da ke yi', 'middleware', '["big key","大key"]'),
('热Key', 're ke yi', 'middleware', '["hot key","热key"]'),
('锁竞争', 'suo jing zheng', 'middleware', NULL),
('内存淘汰', 'nei cun tao tai', 'middleware', NULL),
('增量持久化', 'zeng liang chi jiu hua', 'middleware', NULL),
-- ============ MQ ============
('生产者', 'sheng chan zhe', 'middleware', '["producer"]'),
('消费者', 'xiao fei zhe', 'middleware', '["consumer"]'),
('Broker', 'bu ruo ke', 'middleware', '["broker"]'),
('Topic', 'ta pi ke', 'middleware', '["topic"]'),
('Partition', 'pa ti xiong', 'middleware', '["partition","分区"]'),
('Offset', 'ao fu se te', 'middleware', '["offset","偏移量"]'),
('顺序消息', 'shun xu xiao xi', 'middleware', NULL),
('事务消息', 'shi wu xiao xi', 'middleware', NULL),
('死信队列', 'si xin dui lie', 'middleware', '["dlq","死信"]'),
('消息堆积', 'xiao xi dui ji', 'middleware', NULL),
('削峰填谷', 'xue feng tian gu', 'middleware', '["削峰"]'),
('消息丢失', 'xiao xi diu shi', 'middleware', NULL),
('消息重复', 'xiao xi chong fu', 'middleware', '["重复消费"]'),
('消息中间件', 'xiao xi zhong jian jian', 'middleware', '["mq"]'),
('吞吐量', 'tun tu liang', 'middleware', '["throughput"]'),
('延迟', 'yan chi', 'middleware', '["latency"]');
